/*
 *
 * //My libraries for C++ usage
 * Copyright (c) 2012 Rémi Eté
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */

#include <iostream>
#include <ctime>
#include <fstream>
#include <string>
#include <algorithm>

using namespace std ;


int main(int argc, char* argv [])
{
	if(argc==2 || argc==3) {

	time_t rawtime ;
	struct tm * timeinfo ;
	time ( &rawtime ) ;
	timeinfo = localtime ( &rawtime ) ;
	string Class = string(argv[1]) ;
	string headerfilename = Class + ".h" ;
	string cppfilename = Class + ".C" ;
	string inheritance ;
	if(argc==3) inheritance = argv[2] ;
	else inheritance = "" ;

	// Header Constructor
	string upperHeader = "" ;
	string junk = Class ;
	transform(junk.begin() ,junk.end() ,junk.begin() , ::toupper) ;
	upperHeader = junk ;
	fstream headerfile(headerfilename.c_str(),ios::out) ;
	headerfile << "/*" << endl ;
	headerfile << " *" << endl ;
	headerfile << " * " << headerfilename << " header template generated by fclass" << endl ;
	headerfile << " * Creation date : " << asctime (timeinfo) ;
	headerfile << " * Copyright (c) 2012 Rémi Eté" << endl ;
	headerfile << " * All Right Reserved." << endl ;
	headerfile << " *" << endl ;
	headerfile << " * Use and copying of these libraries and preparation of derivative works" << endl ;
	headerfile << " * based upon these libraries are permitted. Any copy of these libraries" << endl ;
	headerfile << " * must include this copyright notice." << endl ;
	headerfile << " *" << endl ;
	headerfile << " * Written by : R. Eté" << endl ;
	headerfile << " */" << endl ;
	headerfile << endl ;
	headerfile << endl ;
	headerfile << "#ifndef " << upperHeader + "_H" << endl ;
	headerfile << "#define " << upperHeader + "_H" << endl ;
	headerfile << endl ;
	headerfile << "#include <iostream>" << endl ;
	headerfile << "#include <string>" << endl ;
	headerfile << "#include <cstdlib>" << endl ;
	headerfile << "#include <cmath>" << endl ;
	headerfile << endl ;
	headerfile << endl ;
	headerfile << "class " << Class ;
	if(argc==3) headerfile << " : " << inheritance << endl ;
	else headerfile << endl ;
	headerfile << "{" << endl ;
	headerfile << endl ;
	headerfile << "protected :" << endl ;
	headerfile << endl ;
	headerfile << "public :" << endl ;
	headerfile << "	" << Class + "() ;" << endl ;
	headerfile << "	" << "~" + Class + "() ;" << endl ;
	headerfile << endl ;
	headerfile << "}" << endl ;
	headerfile << endl ;
	headerfile << "#endif  // " << upperHeader + "_H" << endl ;
	headerfile.close() ;

	// Implementation file Constructor
	fstream cppfile(cppfilename.c_str() ,ios::out) ;
	cppfile << "/*" << endl ;
	cppfile << " *" << endl ;
	cppfile << " * " << cppfilename << " cpp file template generated by fclass" << endl ;
	cppfile << " * Creation date : " << asctime (timeinfo) ;
	cppfile << " * Copyright (c) 2012 Rémi Eté" << endl ;
	cppfile << " * All Right Reserved." << endl ;
	cppfile << " *" << endl ;
	cppfile << " * Use and copying of these libraries and preparation of derivative works" << endl ;
	cppfile << " * based upon these libraries are permitted. Any copy of these libraries" << endl ;
	cppfile << " * must include this copyright notice." << endl ;
	cppfile << " *" << endl ;
	cppfile << " * Written by : R. Eté" << endl ;
	cppfile << " */" << endl ;
	cppfile << endl ;
	cppfile << endl ;
	cppfile << "#include \"" << headerfilename << "\""<< endl ;
	cppfile << endl ;
	cppfile << "using namespace std ;" << endl ;
	cppfile << endl ;
	cppfile << endl ;
	cppfile << Class << "::"<< Class << "()" << endl ;
	cppfile << "{" << endl ;
	cppfile << "	// Default Constructor" << endl ;
	cppfile << "}" << endl ;
	cppfile << endl ;
	cppfile << Class << "::~"<< Class << "()" << endl ;
	cppfile << "{" << endl ;
	cppfile << "	// Default Destructor" << endl ;
	cppfile << "}" << endl ;
	cppfile << endl ;
	cppfile.close() ;

	}
	return 0 ;
}
