/*
 *
 * //My libraries for C++ usage
 * Copyright (c) 2012 Rémi Eté
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */

#include <iostream>
#include <ctime>
#include <fstream>

using namespace std ;


int main()
{
	time_t rawtime ;
	struct tm * timeinfo ;
	time ( &rawtime ) ;
	timeinfo = localtime ( &rawtime ) ;
	fstream makefile("Makefile",ios::out) ;
	makefile << "################################################" << endl ;
	makefile << "##### Makefile template generated by fmake" << endl ;
	makefile << "##### Creation date : " << asctime (timeinfo) ;
	makefile << "##### CopyRight R. Eté" << endl ;
	makefile << "################################################" << endl ;
	makefile << endl ;
	makefile << endl ;
	makefile << endl ;
	makefile << endl ;
	makefile << "##### Variables :" << endl ;
	makefile << endl ;
	makefile << "CC             = g++" << endl ;
	makefile << "CXXFLAGS       = -Wall -W -pedantic -Wunused-value -Woverloaded-virtual \\ " << endl ;
	makefile << "			-Wshadow -Wfloat-equal -O2 -Wold-style-cast -Wpointer-arith \\ " << endl ;
	makefile << "			-Wcast-align" << endl ;
	makefile << "LDFLAGS        = -Wall -W -pedantic -Wunused-value -Woverloaded-virtual \\ " << endl ;
	makefile << "			-Wshadow -Wfloat-equal -O2 -Wold-style-cast -Wpointer-arith \\ " << endl ;
	makefile << "			-Wcast-align" << endl ;
	makefile << "RM             = rm" << endl ;
	makefile << endl ;
	makefile << endl ;
	makefile << "##### Files" << endl ;
	makefile << endl ;
	makefile << "EXEC           = " << endl ;
	makefile << endl ;
	makefile << "OBJ            = " << endl ;
	makefile << endl ;
	makefile << "SRC            = " << endl ;
	makefile << endl ;
	makefile << "HEADERS        = " << endl ;
	makefile << endl ;
	makefile << endl ;
	makefile << "##### Generic rules" << endl ;
	makefile << "all            : $(EXEC)" << endl ;
	makefile << endl ;
	makefile << endl ;
	makefile << "##### Cleaner" << endl ;
	makefile << endl ;
	makefile << "clean          : " << endl ;
	makefile << "	$(RM) *.o" << endl ;
	makefile << endl ;
	makefile << "mrproper       : clean" << endl ;
	makefile << "	$(RM) $(EXEC)" << endl ;
	makefile << endl ;
	makefile << endl ;
	makefile << "##### End #####" << endl ;

	makefile.close() ;
	return 0 ;
}
