/*
 *
 * MyClass.C cpp file template generated by fclass
 * Creation date : Sun May 20 14:42:30 2012
 * Copyright (c) 2012 Rémi Eté
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */


#include "MyClass.h"

using namespace std ;


MyClass::MyClass()
{
	// Default Constructor
}

MyClass::~MyClass()
{
	// Default Destructor
}

