/*
 *
 * AbstractMenuException.h header template generated by fclass
 * Creation date : Sun May 20 22:11:52 2012
 * Copyright (c) 2012 Rémi Eté
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */


#ifndef ABSTRACTMENUEXCEPTION_H
#define ABSTRACTMENUEXCEPTION_H

#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>


class AbstractMenuException : std::exception
{

protected :


public :
	AbstractMenuException() throw() {} ;
	virtual ~AbstractMenuException() throw() ;
	virtual const char* what() const throw() = 0 ;

}

#endif  // ABSTRACTMENUEXCEPTION_H
