/*
 *
 * MenuException.h header template generated by fclass
 * Creation date : Tue May 22 19:05:17 2012
 * Copyright (c) 2012 Rémi Eté
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */


#ifndef MENUEXCEPTION_H
#define MENUEXCEPTION_H

#include <iostream>
#include <string>
#include <cstdlib>
#include <cmath>


class MenuException : std::exception
{

protected :
	std::string head ;

public :
	MenuException(std::string status , std::string message) throw() ;
	virtual ~MenuException() throw() ;
	virtual const char* what() const throw() ;

};

#endif  // MENUEXCEPTION_H
