/*
 *
 * MenuException.C cpp file template generated by fclass
 * Creation date : Tue May 22 19:05:17 2012
 * Copyright (c) 2012 Rémi Eté
 * All Right Reserved.
 *
 * Use and copying of these libraries and preparation of derivative works
 * based upon these libraries are permitted. Any copy of these libraries
 * must include this copyright notice.
 *
 * Written by : R. Eté
 */


#include "MenuException.h"

using namespace std ;


MenuException::MenuException(std::string status , std::string message)
{
	// Default Constructor
}

MenuException::~MenuException()
{
	// Default Destructor
}

